test: CoisaBonus.java src/base/Descanso.java src/base/Disciplina.java src/base/RegistroTempoOnline.java src/base/AtividadesComplementares.java
			javac -cp ../ CoisaBonus.java && java -cp ../ -ea Lab2_JOAO_VICTOR_DE_SOUZA_LUCENA.CoisaBonus

clear:
			rm *.class && rm src/**/*.class
			