test: CoisaBonus.java src/base/Descanso.java src/base/Disciplina.java src/base/RegistroTempoOnline.java src/base/AtividadesComplementares.java
			javac CoisaBonus.java && java -ea CoisaBonus

clear:
			rm *.class && rm src/**/*.class
			